### ISSUE TITLE
Editorial pass on all content and fix cross-links

### ISSUE THREAD

**Issue by nickstenning** [codessintheclassroom/classroom-material#15]
Take a full pass for voice/style/layout through all of the course notes, and fix all the links between the documents.

**Comment by nickstenning** [comment]
- [x] Setup: #19 
- [x] Building the UI: #20 
- [x] Connecting the API: #23 
- [x] Testing your code: #25
- [x] Submitting a pull request: #26

**Comment by nickstenning** [comment]
Done!
